
//wait for descrition....
//
//
//
#ifndef	__STRING_USER_H
#define	__STRING_USER_H

char String_cmp(char* str1,char* str2);//wait for descrition....
char String_N_cmp(char* str1,char* str2,char N);//wait for descrition....
void CRC8(char data,char* crc);//wait for descrition....
void Num2Str(int num, char*pointer);//wait for descrition....
unsigned int power_of_10(char exp);//wait for descrition....
char Str2Num_char(char* str);//wait for descrition....
float Str2Num_fl(char* str);//wait for descrition....
void Str_copy(char* source,char* des);//wait for descrition....
char Str2Num_nchar(char* str,char n);//wait for descrition....
float Str2Num_nfl(char* str,char n);//wait for descrition....
void Str_N_copy(char* source,char* des,char N);//wait for descrition....
void Array_reset(char* Arr);	
#endif
